//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_satis
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> ktarih { get; set; }
        public Nullable<int> firmakod { get; set; }
        public string sipID { get; set; }
        public Nullable<System.DateTime> sipTarih { get; set; }
        public Nullable<decimal> maliyetHAS { get; set; }
        public Nullable<decimal> iscMaliyetTL { get; set; }
        public Nullable<decimal> panoHas { get; set; }
        public Nullable<decimal> iscHAS { get; set; }
        public string urun { get; set; }
        public string siparisno { get; set; }
    }
}
