//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int K_ID { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciPassword { get; set; }
        public string kullaniciAdiSoyadi { get; set; }
        public string kullaniciEmail { get; set; }
        public string kullaniciResim { get; set; }
        public string kullaniciUnvan { get; set; }
    }
}
