//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Urunler
    {
        public long Id { get; set; }
        public string urunAdi { get; set; }
        public string aciklama { get; set; }
        public string marka { get; set; }
        public string barkod { get; set; }
        public Nullable<int> stok { get; set; }
        public Nullable<decimal> desi { get; set; }
        public Nullable<decimal> kdv { get; set; }
        public string resim { get; set; }
        public string model { get; set; }
        public Nullable<decimal> maliyet { get; set; }
        public Nullable<decimal> sonFiyat { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<System.DateTime> upFiyatTarih { get; set; }
        public Nullable<decimal> panoHas { get; set; }
    }
}
