//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vadeFark
    {
        public long Id { get; set; }
        public Nullable<decimal> gun { get; set; }
        public Nullable<decimal> yuzde { get; set; }
    }
}
