//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ziynetUrunKombin
    {
        public long otosay { get; set; }
        public string barkod { get; set; }
        public string AnaGrup { get; set; }
        public string TezgahGrup { get; set; }
        public string Stokkodu { get; set; }
        public Nullable<decimal> Miktar { get; set; }
    }
}
